/* tslint:disable */
/* eslint-disable */
/**
 * Beat Link Trigger Overlay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { Player, PlayerFromJSON, PlayerFromJSONTyped, PlayerToJSON } from './Player'

/**
 *
 * @export
 * @interface Data
 */
export interface Data {
  /**
   *
   * @type {{ [key: string]: Player | undefined; }}
   * @memberof Data
   */
  collections?: { [key: string]: Player | undefined }
  /**
   *
   * @type {Player}
   * @memberof Data
   */
  master?: Player
  /**
   *
   * @type {{ [key: string]: Player | undefined; }}
   * @memberof Data
   */
  mixers?: { [key: string]: Player | undefined }
  /**
   *
   * @type {{ [key: string]: Player | undefined; }}
   * @memberof Data
   */
  players?: { [key: string]: Player | undefined }
}

export function DataFromJSON(json: any): Data {
  return DataFromJSONTyped(json, false)
}

export function DataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Data {
  if (json === undefined || json === null) {
    return json
  }
  return {
    collections: !exists(json, 'collections')
      ? undefined
      : mapValues(json['collections'], PlayerFromJSON),
    master: !exists(json, 'master') ? undefined : PlayerFromJSON(json['master']),
    mixers: !exists(json, 'mixers') ? undefined : mapValues(json['mixers'], PlayerFromJSON),
    players: !exists(json, 'players') ? undefined : mapValues(json['players'], PlayerFromJSON),
  }
}

export function DataToJSON(value?: Data | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    collections:
      value.collections === undefined ? undefined : mapValues(value.collections, PlayerToJSON),
    master: PlayerToJSON(value.master),
    mixers: value.mixers === undefined ? undefined : mapValues(value.mixers, PlayerToJSON),
    players: value.players === undefined ? undefined : mapValues(value.players, PlayerToJSON),
  }
}
