/* tslint:disable */
/* eslint-disable */
/**
 * Beat Link Trigger Overlay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Time
 */
export interface Time {
  /**
   *
   * @type {string}
   * @memberof Time
   */
  display: string
  /**
   *
   * @type {number}
   * @memberof Time
   */
  frameTenths: number
  /**
   *
   * @type {number}
   * @memberof Time
   */
  frames: number
  /**
   *
   * @type {number}
   * @memberof Time
   */
  minutes: number
  /**
   *
   * @type {number}
   * @memberof Time
   */
  rawMilliseconds: number
  /**
   *
   * @type {number}
   * @memberof Time
   */
  seconds: number
}

/**
 * Check if a given object implements the Time interface.
 */
export function instanceOfTime(value: object): boolean {
  if (!('display' in value)) return false
  if (!('frameTenths' in value)) return false
  if (!('frames' in value)) return false
  if (!('minutes' in value)) return false
  if (!('rawMilliseconds' in value)) return false
  if (!('seconds' in value)) return false
  return true
}

export function TimeFromJSON(json: any): Time {
  return TimeFromJSONTyped(json, false)
}

export function TimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Time {
  if (json == null) {
    return json
  }
  return {
    display: json['display'],
    frameTenths: json['frame-tenths'],
    frames: json['frames'],
    minutes: json['minutes'],
    rawMilliseconds: json['raw-milliseconds'],
    seconds: json['seconds'],
  }
}

export function TimeToJSON(value?: Time | null): any {
  if (value == null) {
    return value
  }
  return {
    display: value['display'],
    'frame-tenths': value['frameTenths'],
    frames: value['frames'],
    minutes: value['minutes'],
    'raw-milliseconds': value['rawMilliseconds'],
    seconds: value['seconds'],
  }
}
